parameters:
#    database.example.class: Company\DatabaseBundle\Example

services:
#    database.example:
#        class: %database.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
